#'rrapidmarkov: Rapid calculation of Markov models for health economic
#'evaluation.
#'
#' This package is designed as a 'no frills' Markov model calculator primarily
#' aimed at health economists conducting cost-effectiveness or cost-utility
#' analyses for health technology assessment.
#'
#' The focus of this package is on speed of computation for efficient conduct
#' of probabilistic analyses.  For example, calculating 10,000 iterations of
#' a 3-state non-stationary Markov model running for 10 cycles takes
#' approximately 3.8 seconds on a single core running at 4GHz.  Output can
#' easily be imported into packages such as BCEA (Baio et al.) and SAVI (Strong
#' et al.) to take advantage of their functionality, such as Value of
#' Information analysis calculations.
#'
#'@section rrapidmarkov functions:
#'
#' runmarkov() - calculates Markov trace for a given transition probability
#' matrix
#'
#' calcvalues() - applies values (eg costs or health state utilities) to Markov
#'   trace to calculate total costs and QALYs
#'
#' psamarkov() - repeatedly calls runmarkov() with sampled transition
#'   probabilities, reported expected Markov traces, lower and upper 95%
#'   credibility limits and raw data
#'
#' psavalues() - applies values to Markov trace generated by psamarkov().
#'
#' converttomatrices() - helper function to format large matrices of sampled
#'   transition probabilities.
#'
#'@section Help pages:
#'
#' userguide - How to guide with worked examples.  Look here for how to use
#'   rrapidmarkov
#'
#' validation-and-speed-check - Report confirming coding accuracy and
#'   speed of computation with large PSA samples.
#'
#' Copyright (C) 2020 Ed Wilson, University of East Anglia, <ed.wilson@uea.ac.uk>
#'
#' July 2020
#'
#'@docType package
#'@name rrapidmarkov
NULL
